# Generated by Django 3.0.8 on 2020-07-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200713_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_price',
            new_name='has_sizes',
        ),
    ]
